optimize app, ready to be published
AREA_OF_IMPROVEMENTS
    Instead of running the program over and over without the user's consent. FIXED

    it will be better to ask the user if they will like to perform another transaction before running it again FIXED

    If an invalid option is entered into the first question, the program should request for a correct option, it should not proceed. FIXED

    The "carry_on" function run once, I will like to keep asking "if the user will like to perform another operation after each operation",
    if yes, the program should run, if No, the program should terminate. FIXED

    Fix the division error, and complete the function for square root FIXED

    I am still trying to figure out how to integrate the power and square opration into the calculator.  FIXED

NOTES
    A converted string case does not work in "IF" statement. So i have to use "Y" or "y", "N" or "N"

    There is a limit for exponential value in Python. If you input a value that exceeds 4300, the program will return a "ValueError". It also recommends a solution. ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

    It does not multiply numbers that begin with zero. It thrown back a syntax error.
         SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers